/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIdagRouteImport } from './routes/_authenticated/idag'
import { Route as AuthenticatedJagRouteImport } from './routes/_authenticated/jag'
import { Route as AuthenticatedListorRouteImport } from './routes/_authenticated/listor'
import { Route as AuthenticatedPlaneratRouteImport } from './routes/_authenticated/planerat'
import { Route as AuthenticatedRutinerRouteImport } from './routes/_authenticated/rutiner'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicRemindersRouteImport } from './routes/api/public/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIdagRoute = AuthenticatedIdagRouteImport.update({
  id: '/idag',
  path: '/idag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJagRoute = AuthenticatedJagRouteImport.update({
  id: '/jag',
  path: '/jag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListorRoute = AuthenticatedListorRouteImport.update({
  id: '/listor',
  path: '/listor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaneratRoute = AuthenticatedPlaneratRouteImport.update({
  id: '/planerat',
  path: '/planerat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRutinerRoute = AuthenticatedRutinerRouteImport.update({
  id: '/rutiner',
  path: '/rutiner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRemindersRoute = ApiPublicRemindersRouteImport.update({
  id: '/api/public/reminders',
  path: '/api/public/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/idag': typeof AuthenticatedIdagRoute
  '/jag': typeof AuthenticatedJagRoute
  '/listor': typeof AuthenticatedListorRoute
  '/planerat': typeof AuthenticatedPlaneratRoute
  '/rutiner': typeof AuthenticatedRutinerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/reminders': typeof ApiPublicRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/idag': typeof AuthenticatedIdagRoute
  '/jag': typeof AuthenticatedJagRoute
  '/listor': typeof AuthenticatedListorRoute
  '/planerat': typeof AuthenticatedPlaneratRoute
  '/rutiner': typeof AuthenticatedRutinerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/reminders': typeof ApiPublicRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/idag': typeof AuthenticatedIdagRoute
  '/_authenticated/jag': typeof AuthenticatedJagRoute
  '/_authenticated/listor': typeof AuthenticatedListorRoute
  '/_authenticated/planerat': typeof AuthenticatedPlaneratRoute
  '/_authenticated/rutiner': typeof AuthenticatedRutinerRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/reminders': typeof ApiPublicRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/idag'
    | '/jag'
    | '/listor'
    | '/planerat'
    | '/rutiner'
    | '/.lovable/oauth/consent'
    | '/api/public/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/idag'
    | '/jag'
    | '/listor'
    | '/planerat'
    | '/rutiner'
    | '/.lovable/oauth/consent'
    | '/api/public/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/idag'
    | '/_authenticated/jag'
    | '/_authenticated/listor'
    | '/_authenticated/planerat'
    | '/_authenticated/rutiner'
    | '/.lovable/oauth/consent'
    | '/api/public/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicRemindersRoute: typeof ApiPublicRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/idag': {
      id: '/_authenticated/idag'
      path: '/idag'
      fullPath: '/idag'
      preLoaderRoute: typeof AuthenticatedIdagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jag': {
      id: '/_authenticated/jag'
      path: '/jag'
      fullPath: '/jag'
      preLoaderRoute: typeof AuthenticatedJagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listor': {
      id: '/_authenticated/listor'
      path: '/listor'
      fullPath: '/listor'
      preLoaderRoute: typeof AuthenticatedListorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planerat': {
      id: '/_authenticated/planerat'
      path: '/planerat'
      fullPath: '/planerat'
      preLoaderRoute: typeof AuthenticatedPlaneratRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rutiner': {
      id: '/_authenticated/rutiner'
      path: '/rutiner'
      fullPath: '/rutiner'
      preLoaderRoute: typeof AuthenticatedRutinerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reminders': {
      id: '/api/public/reminders'
      path: '/api/public/reminders'
      fullPath: '/api/public/reminders'
      preLoaderRoute: typeof ApiPublicRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIdagRoute: typeof AuthenticatedIdagRoute
  AuthenticatedJagRoute: typeof AuthenticatedJagRoute
  AuthenticatedListorRoute: typeof AuthenticatedListorRoute
  AuthenticatedPlaneratRoute: typeof AuthenticatedPlaneratRoute
  AuthenticatedRutinerRoute: typeof AuthenticatedRutinerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIdagRoute: AuthenticatedIdagRoute,
  AuthenticatedJagRoute: AuthenticatedJagRoute,
  AuthenticatedListorRoute: AuthenticatedListorRoute,
  AuthenticatedPlaneratRoute: AuthenticatedPlaneratRoute,
  AuthenticatedRutinerRoute: AuthenticatedRutinerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicRemindersRoute: ApiPublicRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
